baseURL = "https://www.awssecuritylatam.com/"
languageCode = "en"
title = "AWS Security LATAM"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = ""
    description = ""
    email = ""
    phone = ""
    address = "Desde Perú para LATAM 🌎"
    year = 2021
    avatar = ""
    avatarclass = "circle"
    background = ""
    banner = "images/banner.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"
    author = "Gerardo Castro (gerardokaztro.com)"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = true
    showClients = true

    footerEnableContact = false
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Acerca de mí"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Cursos"
    url = "/cursos/"
    weight = 3
[[menu.main]]
    name = "Podcast"
    url = "https://awssecuritylatam.buzzsprout.com/"
    weight = 4
[[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 5
[[menu.main]]
    name = "Libros"
    url = "/libros/"
    weight = 6
[[menu.main]]
    name = "Conferencias"
    url = "/conferencias/"
    weight = 7

[params.disqus]
    site = "gerardokaztro.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "UA-192920482-1"

[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/awssecuritylatam"
    icon = "fab fa-instagram"
    footer = true
    sharethis = true
    network = "instagram"
[[params.social]]
	title = "youtube"
	url = "https://bit.ly/AWSSecurityLATAM"
    icon = "fab fa-youtube"
    footer = true
    sharethis = true
    network = "youtube"
[[params.social]]
	title = "twitch"
	url = "https://www.twitch.tv/awssecuritylatam"
    icon = "fab fa-twitch"
    footer = true
    sharethis = true
    network = "twitch"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/gerardokaztro"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/gerardokaztro"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "blog"
	url = "https://bit.ly/MediumGerardokaztro"
    icon = "fab fa-medium"
    footer = true
    sharethis = true
    network = "medium"
[[params.social]]
	title = "github"
	url = "https://github.com/gerardokaztro"
    icon = "fab fa-github"
    footer = true
    sharethis = true
    network = "github"
[[params.social]]
	title = "Devto"
	url = "https://bit.ly/DevtoGerardokaztro"
    icon = "fab fa-dev"
    footer = true
    sharethis = true
    network = "devto"
